// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cinema/Cinema.tsx": () => import("../components/mockups/cinema/Cinema.tsx"),
  "./components/mockups/ivory/Ivory.tsx": () => import("../components/mockups/ivory/Ivory.tsx"),
  "./components/mockups/obsidian/Obsidian.tsx": () => import("../components/mockups/obsidian/Obsidian.tsx"),
  "./components/mockups/atera-landing/Landing.tsx": () => import("../components/mockups/atera-landing/Landing.tsx")
};
