export interface Template { id: string; label: string; body: string; type: "email" | "sms" | "call" | "objection"; audience: "guest" | "landlord" | "both"; }

export const templates: Template[] = [
  // GUEST EMAILS
  { id: "g-email-inquiry", label: "Initial Inquiry", type: "email", audience: "guest", body: `Subject: Re: Your Enquiry — Atera Stays\n\nHi [Name],\n\nThank you for getting in touch with Atera Stays.\n\nWe've received your enquiry and are checking availability for your requested dates. We'll be in touch within a few hours to confirm details and next steps.\n\nIn the meantime, if you have any questions, please don't hesitate to reply to this email.\n\nWarm regards,\nAtera Stays Team` },
  { id: "g-email-confirm", label: "Booking Confirmation", type: "email", audience: "guest", body: `Subject: Booking Confirmed — Atera Stays\n\nHi [Name],\n\nGreat news — your stay at [Property] is confirmed.\n\nCheck-In: [Date] from [Time]\nCheck-Out: [Date] by [Time]\nAddress: [Property Address]\n\nFull check-in instructions will be sent 24 hours before your arrival. If you have any questions, we're always available.\n\nLooking forward to welcoming you.\n\nAtera Stays Team` },
  { id: "g-email-checkin", label: "Check-In Instructions", type: "email", audience: "guest", body: `Subject: Your Check-In Instructions — [Property]\n\nHi [Name],\n\nYour stay begins tomorrow. Here's everything you need:\n\nAddress: [Full Address]\nKey Access: [Access Instructions]\nWiFi: Network: [SSID] / Password: [Password]\nParking: [Parking Details]\n\nEmergency contact: [Phone Number]\n\nWe hope you have a wonderful stay.\n\nAtera Stays Team` },
  { id: "g-email-midstay", label: "Mid-Stay Check-In", type: "email", audience: "guest", body: `Subject: Checking In — Atera Stays\n\nHi [Name],\n\nHope you're settling in well at [Property].\n\nJust checking everything is to your satisfaction. If there's anything you need or any issues to resolve, please let us know immediately and we'll sort it.\n\nEnjoy the rest of your stay.\n\nAtera Stays Team` },
  { id: "g-email-checkout", label: "Checkout Instructions", type: "email", audience: "guest", body: `Subject: Checkout Tomorrow — Atera Stays\n\nHi [Name],\n\nThis is a reminder that checkout is tomorrow by [Time].\n\nCheckout: Leave keys [Location]. All doors and windows locked.\nItems: Please remove all personal belongings and perishables from the fridge.\n\nThank you for staying with Atera Stays. We hope to welcome you again soon.\n\nAtera Stays Team` },
  { id: "g-email-review", label: "Review Request", type: "email", audience: "guest", body: `Subject: How Was Your Stay? — Atera Stays\n\nHi [Name],\n\nThank you for staying with us at [Property]. We hope it met your expectations.\n\nIf you have a moment, we'd be very grateful for a brief review. Your feedback helps us maintain our standards and helps future guests.\n\n[Review Link]\n\nThank you — it means a lot to us.\n\nAtera Stays Team` },
  // GUEST SMS
  { id: "g-sms-confirm", label: "Booking Confirmation", type: "sms", audience: "guest", body: `Hi [Name], your stay at [Property] is confirmed for [Check-In Date]. Full details to follow by email. Atera Stays — [Phone]` },
  { id: "g-sms-checkin", label: "Check-In Reminder", type: "sms", audience: "guest", body: `Hi [Name], check-in at [Property] is tomorrow from [Time]. Your access instructions will be emailed shortly. Any questions: [Phone]. Atera Stays` },
  // LANDLORD EMAILS
  { id: "l-email-first", label: "First Response", type: "email", audience: "landlord", body: `Subject: Re: Your Property Enquiry — Atera Stays\n\nHi [Name],\n\nThank you for getting in touch with Atera Stays.\n\nWe've received your enquiry about [Property Address] and would love to learn more about your situation and goals.\n\nI'd like to schedule a brief 15-minute call to understand your property better and explain how we work. When would suit you?\n\nLooking forward to speaking.\n\n[Your Name]\nAtera Stays` },
  { id: "l-email-call-booked", label: "Discovery Call Booked", type: "email", audience: "landlord", body: `Subject: Call Confirmed — Atera Stays\n\nHi [Name],\n\nOur call is confirmed for [Date] at [Time].\n\nDial-in: [Link or Number]\n\nOn the call we'll discuss your property, your goals, and explain exactly how Atera Stays works — including guaranteed rent, management responsibilities, and agreement terms.\n\nLooking forward to it.\n\n[Your Name]\nAtera Stays` },
  { id: "l-email-postcall", label: "Post-Call Follow-Up", type: "email", audience: "landlord", body: `Subject: Following Up — Atera Stays\n\nHi [Name],\n\nGreat speaking with you today.\n\nAs discussed, we're interested in [Property Address] and will run our numbers over the next [X] days. I'll come back to you with a formal offer shortly.\n\nIn the meantime, please don't hesitate to reach out with any questions.\n\n[Your Name]\nAtera Stays` },
  { id: "l-email-offer", label: "Formal Offer", type: "email", audience: "landlord", body: `Subject: Formal Offer — [Property Address] — Atera Stays\n\nHi [Name],\n\nFollowing our assessment of [Property Address], we're pleased to present a formal offer:\n\nMonthly Rent: £[Amount]\nAgreement Term: [X] years\nBreak Clause: After [X] months with [X] months notice\nCommencement: [Date]\n\nThis offer is subject to final property inspection and permissions confirmation. Please review and let me know if you'd like to proceed.\n\n[Your Name]\nAtera Stays` },
  { id: "l-email-agreement", label: "Agreement Sent", type: "email", audience: "landlord", body: `Subject: Agreement Ready for Review — Atera Stays\n\nHi [Name],\n\nPlease find attached your Stays Partnership Agreement for [Property Address].\n\nKey terms:\n• Monthly Rent: £[Amount]\n• Term: [X] years from [Date]\n• Break Notice: [X] months after month [X]\n\nWe recommend you review this independently before signing. Once you're ready to proceed, please sign and return.\n\n[Your Name]\nAtera Stays — ATERA INDUSTRIES LTD` },
  { id: "l-email-live", label: "Property Live", type: "email", audience: "landlord", body: `Subject: Your Property is Live — Atera Stays\n\nHi [Name],\n\n[Property Address] is now live on the Atera Stays platform. Guests can enquire and bookings can commence from [Date].\n\nYour first rent payment of £[Amount] will be transferred on [Date].\n\nYou'll receive monthly statements and can contact us any time for updates.\n\nThank you for trusting Atera Stays with your property.\n\n[Your Name]\nAtera Stays` },
  // LANDLORD SMS
  { id: "l-sms-first", label: "First Follow-Up", type: "sms", audience: "landlord", body: `Hi [Name], thanks for your enquiry about [Property]. I'd love to arrange a quick call to explain how we work. When suits you? — Atera Stays [Phone]` },
  { id: "l-sms-7day", label: "7-Day Follow-Up", type: "sms", audience: "landlord", body: `Hi [Name], just following up on your property enquiry with Atera Stays. Still very interested in [Property]. Happy to chat at your convenience. [Phone]` },
];

export const callScripts = [
  { id: "cs-cold", label: "Cold Outreach Script", body: `Opening:\n"Hi, is that [Name]? My name is [Your Name] from Atera Stays. I'm reaching out because we're looking to expand our property portfolio in [Area] and I noticed your property at [Address]. Do you have 5 minutes?"\n\nPitch:\n"We operate a company let model — we take the property on a guaranteed rent basis, handle all the guests, and pay you on the same date every month regardless of occupancy. No voids, no hassle."\n\nClose:\n"I'd love to book a proper call to walk you through the numbers. Are you free [Day] or [Day]?"` },
  { id: "cs-warm", label: "Warm Lead Follow-Up Script", body: `Opening:\n"Hi [Name], it's [Your Name] from Atera Stays. We spoke [X days ago] about your property at [Address]. I just wanted to follow up and see if you've had a chance to think things over?"\n\nHandle hesitation:\n"Completely understand. The main concern most landlords have is [concern] — and the way we handle that is [response]. Does that make sense?"\n\nClose:\n"If you're comfortable, I'd love to send over our formal offer in writing so you can review it with no pressure. Would that work?"` },
  { id: "cs-discovery", label: "Discovery Call Script", body: `Opening:\n"Thanks for making time today, [Name]. I have about 20 minutes blocked. The aim of today's call is just to understand your property and goals, and explain how we work — zero pressure."\n\nQuestions:\n- "Tell me about the property — when was it built, what condition is it in?"\n- "Is it currently tenanted, and when is that arrangement ending?"\n- "What's your ideal scenario — what would a great outcome look like?"\n- "Have you worked with managing agents before?"\n\nPitch the model:\n"So here's how Atera Stays works — we become your company tenant. We pay you a fixed rent each month, we take full responsibility for the property operations, and you have zero involvement in the day-to-day."` },
  { id: "cs-objections", label: "Objection Handling Reference", body: `See the Objection Handling table below for structured responses to the most common landlord objections.` },
];

export const objections = [
  { objection: "I already have a tenant", response: "Understood. When is their current agreement ending? We often work with landlords whose tenants are approaching end of term — we can plan around the timeline so there's no gap.", nextStep: "Find out exact end date, set follow-up reminder." },
  { objection: "I don't want short-term lets", response: "That's completely fair. Our Property Management service doesn't involve short-lets at all — we place long-term tenants and handle full management. Would that model suit you better?", nextStep: "Pivot to Management service." },
  { objection: "The rent you're offering is too low", response: "The figure we offer accounts for us absorbing all void periods, maintenance coordination, and operational costs. Many landlords find the consistency more valuable than chasing a higher headline rate. Can I show you the numbers?", nextStep: "Share deal breakdown." },
  { objection: "I want to manage it myself", response: "Completely respect that. Our Management service is ideal if you want to keep control of the asset — we simply handle the admin, compliance, and tenant communication while you retain ownership and oversight.", nextStep: "Discuss Management only." },
  { objection: "I need to think about it", response: "Of course, no rush at all. To help you make the decision, can I send our full agreement template so you can review terms in your own time? That way you have everything in writing.", nextStep: "Send agreement, set 7-day follow-up." },
  { objection: "What about my mortgage lender", response: "Good question. Many buy-to-let mortgages permit company lets — it depends on your lender and your policy. We'd confirm this with you as part of the due diligence before signing anything.", nextStep: "Advise them to check with lender. Note in CRM." },
];
